#!/usr/bin/env bash
# Fizzbuzz as a bash script
a=1
while [ $a -le 100 ]; do if [ $((a % 15)) -eq 0 ]; then echo 'FizzBuzz'; elif [ $((a % 5)) -eq 0 ]; then echo 'Buzz'
elif [ $((a % 3)) -eq 0 ]; then echo 'Fizz'; else echo $a; fi
((a++))
done
