#!/usr/bin/env bash
# comment
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s,listen 80 default_server;,listen 8080 default_server;," /etc/nginx/sites-enabled/default
sed -ri "s,listen \[::]:80.+;,listen [::]:8080 default_server ipv6only=on;," /etc/nginx/sites-enabled/default
su -c "service nginx start" nginx
