#!/usr/bin/env bash
# comment
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -ri "s,\listen\s80\sdefault,listen 8080 default," /etc/nginx/sites-enabled/default
sed -ri "s,\[::\]:80,[::]:8080," /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
